driver:
  name: vagrant
  driver_config:
    ssl_verify_mode: ":verify_none"
  # customize:
  #   cpus: 4
  #   memory: 8192
  #   accelerate3d: "off"
  #   accelerate2dvideo: "off"
  #   audio: "none"
  #   usbcardreader: "off"
  #   vrde: "off"
  #   usb: "off"
  #   nictype1: "82540EM"
  #   clipboard: "disabled"
  #nestedpaging: "off

  transport:
    max_ssh_sessions: 2

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: false
  #require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  # require_pip3: true
  ansible_verbose: true
  ansible_binary_path: /usr/bin
  roles_path: spec/ansible/roles
  galaxy_ignore_certs: true

platforms:
- name: ubuntu-18.04

  driver:
    box: generic/ubuntu1804

lifecycle:
  pre_create:
  - local: killall -9 VBoxHeadless && vagrant destroy || true
  pre_converge:
  - remote: |
      echo "NOTICE - Updating the vagrant user to keep sudo working"
      sudo chage -d $(( $( date +%s ) / 86400 )) vagrant
      echo "NOTICE - updating vagrant sudo config"
      sudo chmod 600 /etc/sudoers && sudo sed -i'' "/vagrant/d" /etc/sudoers && sudo chmod 400 /etc/sudoers
      sudo apt -y upgrade
      sudo apt -y install ansible

