platforms:
- name: ubuntu-18.04

driver:
  name: ec2
  # subnet_filter:
  #   tag: 'Default'
  #   value: '*public*'
  metadata_options:
    http_tokens: required
    http_put_response_hop_limit: 1
    instance_metadata_tags: enabled
  instance_type: t2.medium
  associate_public_ip: true
  interface: public
  skip_cost_warning: true
  privileged: true
  instance_initiated_shutdown_behavior: terminate

provisioner:
  name: ansible_playbook
  hosts: all
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_binary_path: /usr/local/bin
  require_pip3: true
  ansible_verbose: true
  roles_path: spec/ansible/roles
  galaxy_ignore_certs: true
  requirements_path: spec/ansible/roles/requirements.yml
  requirements_collection_path: spec/ansible/roles/requirements.yml
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>

suites:
- name: vanilla
  provisioner:
    playbook: spec/ansible/ubuntu-stig-vanilla.yml
  driver:
    tags:
      Name: Vanilla-<%= ENV['USER'] %>
      CreatedBy: test-kitchen

- name: hardened
  provisioner:
    playbook: spec/ansible/ubuntu-stig-hardening.yml
  driver:
    tags:
      Name: Hardened-<%= ENV['USER'] %>
      CreatedBy: test-kitchen

lifecycle:
  pre_converge:
  - remote: |
      # echo "+++ Refreshing DNF package cache +++"
      # sudo dnf -y clean all
      echo ""
      echo "+++ Updating APT Packages +++"
      sudo apt -y upgrade
      echo ""
      # echo "+++ Installing needed packages for workflow and utility +++\n\n"
      sudo apt -y install python3 python3-pip libxml2 libxml2-dev libxslt-dev python-dev
      echo ""
      echo "+++ Installing Python 3.6 and Ansible +++\n\n"
      #export PATH=/usr/local/bin:$PATH
      # sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
      # pip3 install --user --upgrade pip
      # sudo python3 -m pip install ansible jmespath passlib lxml xmltodict --y
      echo ""
      echo "+++ Updating the ec2-user to keep sudo working after hardening phase +++\n\n"
      sudo chage -d $(( $( date +%s ) / 86400 )) ec2-user
      echo ""
      echo "+++ updating ec2-user sudo config for hardening phase +++\n\n"
      sudo chmod 600 /etc/sudoers && sudo sed -i'' "/ec2-user/d" /etc/sudoers && sudo chmod 400 /etc/sudoers
      echo "+++ updating ubuntu sudo config for hardening phase +++\n\n"
      sudo chmod 600 /etc/sudoers && sudo sed -i'' "/ubuntu/d" /etc/sudoers && sudo chmod 400 /etc/sudoers
      sudo apt-get install -y wget apt-transport-https software-properties-common
  post_converge:
  - remote: |
      # # Download the Microsoft repository keys
      wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
      # # Register the Microsoft repository keys
      sudo dpkg -i packages-microsoft-prod.deb
      # # Delete the Microsoft repository keys file
      rm packages-microsoft-prod.deb
      # # Update the list of packages after we added packages.microsoft.com
      sudo apt-get update
      # ###################################
      # # Install PowerShell
      sudo apt-get install -y powershell
      ### ADD Evaluate STIG HERE ###

transport:
  name: ssh
  #https://github.com/neillturner/kitchen-ansible/issues/295
  max_ssh_sessions: 2
