- name: Install audispd-plugins required package
  apt:
    name:
      - audispd-plugins
    state: latest
  tags:
    - V-129153
    - V-219162

- name: Install Advanced Intrusion Detection Environment (AIDE) required package
  apt:
    name:
      - aide
    state: latest
  tags:
    - V-129343

- name: The Ubuntu operating system audit event multiplexor must be configured to off-load audit logs onto a different system or storage media from the system being audited
  lineinfile:
    dest: /etc/audisp/audisp-remote.conf
    regexp: "^(#)?remote_server"
    line: "remote_server = {{ security_audisp_remote_server }}"
  notify:
    - restart auditd
  tags:
    - V-219162

- name: The Ubuntu operating system audit event multiplexor must be configured to off-load audit logs onto a different system or storage media from the system being audited
  lineinfile:
    dest: /etc/audisp/plugins.d/au-remote.conf
    regexp: "^(#)?active"
    line: "active = yes"
  notify:
    - restart auditd
  tags:
    - V-219162


- name: The Ubuntu operating system audit event multiplexor must be configured to off-load audit logs onto a different system or storage media from the system being audited
  lineinfile:
    dest: //etc/audisp/plugins.d/au-remote.conf
    regexp: "^(#)?remote_server"
    line: "remote_server = {{ security_audisp_remote_server }}"
  notify:
    - restart auditd
  tags:
    - V-219162

- name: Update Audit Rules configuration with STIG Rules
  ansible.builtin.template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/stig.rules
    owner: root
    group: root
    mode: '0640'
  notify:
    - restart auditd
  when:
    - ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
    - no_reboot_needed | bool
    - configure_strategy | bool
    - audit_rules | bool
    - medium_severity | bool
    - low_disruption | bool
    - low_complexity | bool
  tags:
    - V-219240
    - V-219241
    - V-219242
    - V-219243
    - V-219244
    - V-219245
    - V-219246  
    - V-219247
    - V-219248
    - V-219249           
    - V-219250           
    - V-219251           
    - V-219252           
    - V-219253           
    - V-219254           
    - V-219255
    - V-219256
    - V-219257
    - V-219261
    - V-219262    
    - V-219278
    - V-219279
    - V-219280
    - V-219282
    - V-219283
    - V-219284
    - V-219285
    - V-219286
    - V-219287
    - V-219288
    - V-219289
    - V-219290
    - V-219291
    - V-219292
    - V-219293    
    - V-219294
    - V-219295
    - DISA-STIG-UBTU-18-010317    
    - DISA-STIG-UBTU-18-010318    
    - DISA-STIG-UBTU-18-010319    
    - DISA-STIG-UBTU-18-010320    
    - DISA-STIG-UBTU-18-010321    
    - DISA-STIG-UBTU-18-010322 
    - DISA-STIG-UBTU-18-010323
    - DISA-STIG-UBTU-18-010324
    - DISA-STIG-UBTU-18-010325   
    - DISA-STIG-UBTU-18-010326      
    - DISA-STIG-UBTU-18-010327
    - DISA-STIG-UBTU-18-010328
    - DISA-STIG-UBTU-18-010329
    - DISA-STIG-UBTU-18-010330
    - DISA-STIG-UBTU-18-010331
    - DISA-STIG-UBTU-18-010332
    - DISA-STIG-UBTU-18-010333
    - DISA-STIG-UBTU-18-010334
    - DISA-STIG-UBTU-18-010338    
    - DISA-STIG-UBTU-18-010339 
    - DISA-STIG-UBTU-18-010355
    - DISA-STIG-UBTU-18-010356
    - DISA-STIG-UBTU-18-010357
    - DISA-STIG-UBTU-18-010366
    - DISA-STIG-UBTU-18-010367
    - DISA-STIG-UBTU-18-010368
    - DISA-STIG-UBTU-18-010369
    - DISA-STIG-UBTU-18-010370
    - DISA-STIG-UBTU-18-010375
    - DISA-STIG-UBTU-18-010376
    - DISA-STIG-UBTU-18-010377
    - DISA-STIG-UBTU-18-010378    
    - DISA-STIG-UBTU-18-010379    
    - DISA-STIG-UBTU-18-010390    
    - NIST-800-171-3.1.7
    - NIST-800-53-AC-6(9)
    - NIST-800-53-AU-12(c)
    - NIST-800-53-AU-2(d)
    - NIST-800-53-CM-6(a)
    - PCI-DSS-Req-10.2.7
    - audit_rules
    - configure_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed

- name: Change file permissions for Security Tools
  ansible.builtin.file:
    path: '{{ item }}'
    mode: '0755'
  loop:
    '{{ security_audit_tools }}'
  tags:
    - V-219195

- name: Change file ownership for Security Tools
  ansible.builtin.file:
    path: '{{ item }}'
    group: 'root'
  loop:
    '{{ security_audit_tools }}'
  tags:
    - V-219197

- name: The Ubuntu operating system must be configured so that audit log files cannot be read or write-accessible by unauthorized users.
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: "^(#)?log_group"
    line: "log_group = root"
  notify:
    - restart auditd
  tags:
    - V-219228

- name: The Ubuntu operating system must be configured so that audit log files cannot be read or write-accessible by unauthorized users.
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: "^(#)?action_mail_acct"
    line: "action_mail_acct = root"
  notify:
    - restart auditd
  tags:
    - V-219226

- name: The Ubuntu operating system must shut down by default upon audit failure (unless availability is an overriding concern).
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: "^(#)?disk_full_action"
    line: "disk_full_action = HALT"
  notify:
    - restart auditd
  tags:
    - V-219227

- name: Change file permissions for Audit Logfile
  ansible.builtin.file:
    path: '{{ security_audit_log }}'
    mode: '0600'
  tags:
    - V-219228

- name: Change file ownership for Audit Logfile
  ansible.builtin.file:
    path: '{{ security_audit_log }}'
    group: 'root'
  tags:
    - V-219229

- name: Change file ownership for Audit Logfile Folder
  ansible.builtin.file:
    path: '{{ security_audit_log_directory }}'
    owner: 'root'
  tags:
    - V-219232

- name: Change file group for Auditd Rules Folder
  ansible.builtin.file:
    path: '{{ security_audit_directory }}'
    group: 'root'
    recurse: yes
  tags:
    - V-219236

- name: "The Ubuntu operating system must use cryptographic mechanisms to protect the integrity of audit tools. Set audit=1 at boot."
  replace:
      dest: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.*audit)\"[^\"]*)(\".*)'
      replace: '\1 audit=1\2'
  when:
    - ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
  notify:
      - generate new grub config
  tags:
      - V-219149