- name: Ensure ufw is installed
  package:
    name: ufw
    state: present
  when:
    - package_ufw_installed | bool
    - no_reboot_needed | bool
    - medium_severity | bool
    - enable_strategy | bool
    - low_disruption | bool
    - low_complexity | bool
  tags:
    - V-219161
    - DISA-STIG-UBTU-18-010023
    - NIST-800-53-CM-6(a)

- name: Enable service ufw
  block:
    - name: Gather the package facts
      package_facts:
        manager: auto
    - name: Enable service ufw
      service:
        name: ufw
        enabled: 'yes'
        state: started
      when:
      - '"ufw" in ansible_facts.packages'
  when:
  - ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
  - service_ufw_enabled | bool
  - no_reboot_needed | bool
  - medium_severity | bool
  - enable_strategy | bool
  - low_disruption | bool
  - low_complexity | bool
  tags:
  - V-219337
  - DISA-STIG-UBTU-18-010507
  - NIST-800-171-3.1.3
  - NIST-800-171-3.4.7
  - NIST-800-53-AC-4
  - NIST-800-53-CA-3(5)
  - NIST-800-53-CM-6(a)
  - NIST-800-53-CM-7(b)
  - NIST-800-53-SC-7(21)
  - enable_strategy
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - service_ufw_enabled
