- name: Set Account Expiration Following Inactivity
  lineinfile:
    create: true
    dest: /etc/default/useradd
    regexp: ^INACTIVE
    line: INACTIVE={{ var_account_disable_post_pw_expiration }}
  tags:
  - V-219326
  - CJIS-5.6.2.1.1
  - DISA-STIG-UBTU-18-010445
  - NIST-800-171-3.5.6
  - NIST-800-53-AC-2(3)
  - NIST-800-53-CM-6(a)
  - NIST-800-53-IA-4(e)
  - PCI-DSS-Req-8.1.4
  - account_disable_post_pw_expiration
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - restrict_strategy
  when:
  - account_disable_post_pw_expiration | bool
  - no_reboot_needed | bool
  - restrict_strategy | bool
  - medium_severity | bool
  - low_disruption | bool
  - low_complexity | bool
  
- name: Prevent direct login into the root account
  user:
    name: root
    password_lock: true
  tags:
    - V-219168
    - DISA-STIG-UBTU-18-010036
    - NIST-800-171-3.1.1
    - NIST-800-171-3.1.5
    - NIST-800-53-AC-6
    - NIST-800-53-CM-6(a)
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy
    - prevent_root_login
  when:
    - no_reboot_needed | bool
    - restrict_strategy | bool
    - prevent_root_login | bool
    - medium_severity | bool
    - low_disruption | bool
    - low_complexity | bool
    
- name: Enable GNOME3 Login Warning Banner
  ini_file:
    dest: /etc/gdm3/greeter.dconf-defaults
    section: org/gnome/login-screen
    option: banner-message-enable
    value: 'true'
    create: true
    no_extra_spaces: true
  tags:
    - V-219167
    - DISA-STIG-UBTU-18-010035
    - NIST-800-171-3.1.9
    - NIST-800-53-AC-8(a)
    - NIST-800-53-AC-8(b)
    - NIST-800-53-AC-8(c)
    - dconf_gnome_banner_enabled
    - low_complexity
    - medium_disruption
    - medium_severity
    - no_reboot_needed
  when:
    - dconf_gnome_banner_enabled | bool
    - no_reboot_needed | bool
    - medium_severity | bool
    - medium_disruption | bool
    - low_complexity | bool
  
- name: Set the GNOME3 Login Warning Banner Text
  ini_file:
    dest: /etc/gdm3/greeter.dconf-defaults
    section: org/gnome/login-screen
    option: banner-message-text
    value: '{{ banner_message_text_gui }}'
    create: true
    no_extra_spaces: true
  tags:
    - V-219167
    - DISA-STIG-UBTU-18-010035
    - NIST-800-171-3.1.9
    - NIST-800-53-AC-8(a)
    - NIST-800-53-AC-8(c)
    - dconf_gnome_banner_enabled
    - low_complexity
    - medium_disruption
    - medium_severity
    - no_reboot_needed
  when:
    - dconf_gnome_banner_enabled | bool
    - no_reboot_needed | bool
    - medium_severity | bool
    - medium_disruption | bool
    - low_complexity | bool