name: Verify the Baseline using Vagrant

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  my-job:
    name: Validate my profile
    runs-on: macos-latest
    env:
      CHEF_LICENSE: accept-silent
      KITCHEN_LOCAL_YAML: kitchen.vagrant.yml
    strategy:
      matrix:
        suite: ['vanilla', 'hardened']
      fail-fast: false
    steps:
      - name: Add jq for output formatting
        run: brew install jq
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Disable ri and rdoc
        run: 'echo "gem: --no-ri --no-rdoc" >> ~/.gemrc'
      - run: bundle install
      - name: Regenerate current `profile.json`
        run: |
          bundle exec inspec json . | jq . > profile.json
      - name: Lint the Inspec profile
        run: bundle exec inspec check .
      - name: Run kitchen test
        run: bundle exec kitchen test --destroy=always ${{ matrix.suite }}-ubuntu-18.04 || true
      - name: Display our ${{ matrix.suite }} results summary
        run: bundle exec inspec_tools summary -j spec/results/ubuntu-18.04_${{ matrix.suite }}.json --json-counts | jq .
      - name: Ensure the scan meets our ${{ matrix.suite }} results threshold
        run: bundle exec inspec_tools compliance -j spec/results/ubuntu-18.04_${{ matrix.suite }}.json -f ${{ matrix.suite }}.threshold.yml
      - name: Save Test Result JSON
        uses: actions/upload-artifact@v2
        with:
          path: spec/results/
